ShopMall/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

ShopMall/ShopMall/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from django.conf import settings  #获取配置文件
from django.conf.urls.static import static  #获取静态文件

urlpatterns = [
    url(r'^admin/', xadmin.site.urls),

    url(r'', include('goods.urls')),
    url(r'^home/', include('home.urls')),


    url(r'^ueditor/',include('DjangoUeditor.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  #图片显示设置

ShopMall/home/urls.py
from django.conf.urls import url
from django.contrib import admin
import xadmin
from . import views

urlpatterns = [
    url(r'^addcar/',views.addcar,name='addcar'),
    url(r'^showcar/',views.showcar,name='showcar'),
    url(r'^delcar/',views.delcar,name='delcar'),
    url(r'^order/',views.order,name='order'),
    url(r'^my_center/',views.my_center,name='my_center'),
    url(r'^my_collect/',views.my_collect,name='my_collect'),
    url(r'^shop_address/',views.shop_address,name='shop_address'),
    url(r'^change_pwd/',views.change_pwd,name='change_pwd'),
]

ShopMall/goods/models.py
from django.db import models

# Create your models here.
from DjangoUeditor.models import UEditorField

#商品信息
class goods(models.Model):
    delete=((0,'否'),(1,'是'))
    name=models.CharField(max_length=150,verbose_name='商品名名称')
    title=models.CharField(max_length=150,verbose_name='商品说明')
    price=models.DecimalField(max_digits=10,decimal_places=2,verbose_name='价格')
    promotion_price=models.DecimalField(max_digits=10,decimal_places=2,verbose_name='促销价')
    type_id=models.ForeignKey('goods_type',default=1,verbose_name='分类ID')
    disabled=models.IntegerField(default=0,choices=delete)
    stoc=models.IntegerField(default=0,verbose_name='库存')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='商品'
        verbose_name_plural='商品信息'

#商品介绍
class goods_introduce(models.Model):
    content=UEditorField(u'产品特色',height=300,width=800,max_length=10240000000000000,default=u'',blank=True,imagePath='ueditor/',toolbars='full',filePath='files/')
    content2=UEditorField(u'产品功能',height=300,width=800,max_length=10240000000000000,default=u'',blank=True,imagePath='ueditor/',toolbars='full',filePath='files/')
    content3=UEditorField(u'产品细节',height=300,width=800,max_length=10240000000000000,default=u'',blank=True,imagePath='ueditor/',toolbars='full',filePath='files/')
    content4=UEditorField(u'产品信息',height=300,width=800,max_length=10240000000000000,default=u'',blank=True,imagePath='ueditor/',toolbars='full',filePath='files/')


    afte_sale=UEditorField(u'售后',height=300,width=800,max_length=10240000000000000,default=u'',blank=True,imagePath='ueditor/',toolbars='full',filePath='files/')
    goods=models.OneToOneField('goods',default=1,to_field='id')

    class Meta:
        verbose_name='商品介绍'
        verbose_name_plural='商品详细信息'

#商品图片
class goods_img(models.Model):
    path=models.ImageField(upload_to='goods',max_length=200,verbose_name='图片路径')
    goods=models.ForeignKey('goods',default=1,verbose_name='商品ID')  #一对多外键对应商品ID
    status=models.IntegerField(default=0,verbose_name='状态')
    # def __str__(self):
    #     return self.goods

   #给字段直接显示缩略图
    def img_tab(self):

        return  "<img src='/media/%s' width='50' height='50' />" %(self.path)

    img_tab.short_description='图片'
    img_tab.allow_tags = True

    # end给字段直接显示缩略图

    #该字段起别名
    class Meta:
        verbose_name='商品图片'
        verbose_name_plural='商品内容图片'

    #end该字段起别名

#商品评价
class goods_evaluate(models.Model):
    start=((1,1),(2,2),(3,3),(4,4),(5,5),)
    start_type=((1,'差评'),(2,'中评'),(3,'好评'),)
    uid=models.ForeignKey('home.member',default=1,verbose_name='用户ID')
    create_time=models.DateTimeField(auto_now_add=True,verbose_name='评价时间')
    goods_id=models.ForeignKey('goods',default=1,verbose_name='商品ID')

    evaluate_content=models.TextField(verbose_name='评价内容')
    evaluate_img=models.ImageField(blank=True,upload_to='goods',max_length=200,verbose_name='评价图片路径')

    evaluate_star=models.IntegerField(default=5,verbose_name='评价星级',choices=start)
    evaluate_type=models.IntegerField(default=5,verbose_name='好评度',choices=start_type)


    # 给字段直接显示缩略图
    def img_tab(self):

        return "<img src='/media/%s' width='50' height='50' />" % (self.evalute_img)

    img_tab.short_description = '图片'
    img_tab.allow_tags = True

    # end给字段直接显示缩略图

    class Meta:
        verbose_name='商品评价'
        verbose_name_plural='商品评价信息'

#商品推荐
class goods_tj(models.Model):
    goodstj_name=models.ForeignKey('goods',verbose_name='商品ID')
    goodstj_sort_id=models.IntegerField(default=1)
    goodstj_start_time=models.DateTimeField()
    goodstj_end_time=models.DateTimeField()

    class Meta:
        verbose_name='商品推荐'#字段名
        verbose_name_plural='商品推荐表'#表名
#商品分类
class goods_type(models.Model):
    #类别名
    name=models.CharField(max_length=100,verbose_name='类别名')
    parent_id=models.IntegerField(default=0,verbose_name='父类ID')


    class Meta:
        verbose_name='商品分类'#字段名
        verbose_name_plural='商品分类表表'#表名
    def __str__(self):
        return self.name

ShopMall/home/models.py
from django.db import models

# Create your models here.


class member(models.Model):       #会员信息表

    sex_choice=((0,'不设置'),(1,'男'),(2,'女'))

    # id=models.AutoField(primary_key=True,)                    #主键自动增长一般不用创建
    nickname=models.CharField(max_length=30,default='admin',verbose_name='昵称')
    name=models.CharField(max_length=30,unique=True,verbose_name='用户名')
    password=models.CharField(max_length=32,verbose_name='用户密码')
    sex=models.IntegerField(default=0,choices=sex_choice,verbose_name='性别')  #choice给个下拉框
    email=models.CharField(max_length=40,default=0,verbose_name='邮箱')
    phone=models.CharField(max_length=11,default=0,null=False,verbose_name='手机')
    qq=models.CharField(max_length=20,default=0,null=False,verbose_name='QQ')

    create_time=models.DateTimeField(auto_now_add=True,verbose_name='账户创建时间')         #创建帐户时间
    last_login_time=models.DateTimeField(auto_now=True, verbose_name='最后一次登录时间')                      #每一次操作时间记录,参数是auto_now=默认不写就是


    def __str__(self):
        return self.name
    class Meta:
        verbose_name='用户'
        verbose_name_plural='用户信息'


class shopping_car(models.Model):
    user=models.ForeignKey('member',default=1,verbose_name='用户名')
    number=models.IntegerField(default=1,verbose_name='数量')
    goods=models.ForeignKey('goods.goods',default=1,verbose_name='商品ID')
    uptime=models.DateTimeField(auto_now=True,verbose_name='更新时间')

    def __str__(self):
        return self.user

    class Meta:
        verbose_name='购物车商品信息'
        verbose_name_plural='购物车表'

ShopMall/home/views.py
from django.shortcuts import render
from .models import shopping_car
from django.shortcuts import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.db.models import Q,F,Sum

# 购物车添加商品
def addcar(request):
    a = request.COOKIES.get('uid', 1)
    # return HttpResponse('进入')
    # print('进入')
    # print(request.POST)
    if a!=1:
        try:
            gid=request.POST['gid']
            num=request.POST['num']
            # print(num)
        except:
            return HttpResponse('商品不存在')
        c=shopping_car.objects.filter(goods_id=gid).values_list('goods_id',flat=True)

        gid=int(gid)
        if gid   in c:
            list="alert('成功添加到购物车')"
            shopping_car.objects.filter(goods=gid).update(number=F('number') + num)
            return HttpResponseRedirect(reverse('show',args=(gid,)))
            # return render(request,'goods/show_details.html')

        else:

            shopcar = shopping_car()
            shopcar.user_id = a
            shopcar.goods_id = gid
            shopcar.number = num
            shopcar.save()
            return HttpResponseRedirect(reverse('show',args=(gid,)))
    else:
        return HttpResponseRedirect(reverse('signin'))

# 删除购物车商品
def delcar(request):
    a=request.GET.get('p')
    shopping_car.objects.filter(id=a).delete()
    return HttpResponse(a)

#请求 购物车展示1
def showcar(request):
    return render(request, 'home/shopping_car.html')

#请求 个人中心
def my_center(request):
    return render(request, 'home/my_center.html')
    pass

#请求 我的订单
def order(request):
    return render(request,'home/user_page1.html')

#请求 我的收藏
def my_collect(request):
    return render(request, 'home/user_page2.html')
    pass

#请求 收货地址
def shop_address(request):
    return render(request, 'home/user_page3.html')
    pass

#请求 修改密码
def change_pwd(request):
    return render(request, 'home/user_page4.html')
    pass

ShopMall/templates/home/findPassword_step1.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
<link rel="stylesheet" href="css/pub.css"/>
<link rel="stylesheet" href="css/log.css"/>
<link rel="stylesheet" href="css/color.css"/>
<script src="js/jquery.min.js"></script>

</head>

<body>
<!--header-->
<div class="zg-header cont clearfix">
    <a href="#" target="_blank" class="zg-header-logo fl"><img src="images/u_logo.jpg" alt="小U商城"/></a>
    <span class="zg-header-title fl">找回密码</span>
</div>
<!--header-->

<div class="reset_w">
	<div class="reset">
    	<h1>找回密码</h1>
    	<form>
        	<div class="ipt_mail_w">
                <div class="ipt_mail_c clearfix">
                    <b class="ipt_mail_iw"><i class="ipt_mail_i"></i></b>
                    <input type="text" value="请输入账号" class="ipt_mail">
                </div>
                <p class="error_info">请输入账号</p>
            </div>
        	<div class="ipt_code_w">
                <div class="ipt_code_c">
                    <input type="text" value="验证码" class="ipt_code">
                    <img src="images/code.jpg" width="69" height="38">
                    
                </div>
                <p class="error_info">请输入验证码</p>
            </div>
        	<input type="submit" value="下一步" class="nextStep">
        </form>
    </div>
</div>
<!--footer-->
<div class="zg-footer-box">
    <p>Copyright © 2010-2016 小U商城 版权所有 保留一切权利</p>
    <p>京ICP备10218183号 京ICP证161188号 京公网安备 11010802020593号 出版物经营许可证新出发京批字第直130052号</p>
</div>
<!--footer-->
<script src="js/pub.js"></script>
</body>
</html>

ShopMall/templates/home/findPassword_step2.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
<link rel="stylesheet" href="css/pub.css"/>
<link rel="stylesheet" href="css/log.css"/>
<link rel="stylesheet" href="css/color.css"/>
<script src="js/jquery.min.js"></script>
</head>
<body>
<!--header-->
<div class="zg-header cont clearfix">
    <a href="#" target="_blank" class="zg-header-logo fl"><img src="images/u_logo.jpg" alt="小U商城"/></a>
    <span class="zg-header-title fl">重置密码</span>
</div>
<!--header-->
<div class="reset_w">
	<div class="reset reset_4">
    	<h1>重置密码</h1>
        <p>账号：zhangsan</p>
    	<form>
            <div>
                <input type="text" value="请输入新密码" class="reset_password_t password_t">
                <input type="password" value="" class="reset_password ipt_password">
        	</div>
            <div>
                <input type="text" value="请再次输入新密码" class="reset_password_t password_t">
                <input type="password" value="" class="reset_password ipt_password">
            </div>
        	<input type="submit" value="下一步" class="nextStep">
        </form>
    </div>
</div>
<!--footer-->
<div class="zg-footer-box">
    <p>Copyright © 2010-2016 小U商城 版权所有 保留一切权利</p>
    <p>京ICP备10218183号 京ICP证161188号 京公网安备 11010802020593号 出版物经营许可证新出发京批字第直130052号</p>
</div>
<!--footer-->
<script src="js/pub.js"></script>
</body>
</html>

ShopMall/templates/home/findPassword_step3.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
<link rel="stylesheet" href="css/pub.css"/>
<link rel="stylesheet" href="css/log.css"/>
<link rel="stylesheet" href="css/color.css"/>
<script src="js/jquery.min.js"></script>
</head>
<body>
<!--header-->
<div class="zg-header cont clearfix">
    <a href="#" target="_blank" class="zg-header-logo fl"><img src="images/u_logo.jpg" alt="小U商城"/></a>
    <span class="zg-header-title fl">重置密码</span>
</div>
<!--header-->
<div class="reset_w">
	<div class="reset reset_5">
    	<h1>重置密码</h1>
        <p>密码重置成功！<br/>请妥善保存您的密码</p>
    	<form>
        	<input type="submit" value="去登录" class="nextStep">
        </form>
    </div>
</div>
<!--footer-->
<div class="zg-footer-box">
    <p>Copyright © 2010-2016 小U商城 版权所有 保留一切权利</p>
    <p>京ICP备10218183号 京ICP证161188号 京公网安备 11010802020593号 出版物经营许可证新出发京批字第直130052号</p>
</div>
<!--footer-->
<script src="js/pub.js"></script>
</body>
</html>

ShopMall/templates/home/my_center.html
{% include 'public/public_head.html' %}
{% load staticfiles %}
{# 内容#}
<div class="cont user user_0 clearfix">
	<div class="user_menu"> 
        <dl>
            <dt class="colorChange">个人中心</dt>
            <dd><a href="{% url 'order' %} }" target="_blank">我的订单</a></dd>
            <dd><a href="{% url 'my_collect' %}" target="_blank">我的收藏</a></dd>
            <dd><a href="#" target="_blank">我的优惠券</a></dd>
            <dd><a href="{% url 'shop_address' %}" target="_blank">我的收货地址</a></dd>
            <dd><a href="#" target="_blank">商品评价</a></dd>
            <dd><a href="{% url 'change_pwd' %}" target="_blank">修改密码</a></dd>
        </dl>
    </div>
    <!--  个人信息内容  -->
    <div class="user_right fr">
        <h3 class="user_title">个人信息</h3>
		<div class="user_rc clearfix">
			<p>亲爱的<span>d***i</span>，填写真实的资料，有助于好友找到你哦。</p>
          <form action="#" >
          <table width="500" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <th class="zg_person_th">当前头像：</th>
                <td>
                	<img src="{% static 'images/zg_person.jpg' %}" width="120" height="120" alt="我的头像">
                    <label class="userInfo_file"><input type="file">上传头像</label>
                </td>
              </tr>
              <tr>
                <th>邮箱帐号：</th>
                <td class="user_mail">
                	<span>zhangsan@126.com</span>
                    <span>未验证 <a href="#">去验证</a></span>
                    <span>已验证 <a href="#">修改邮箱</a></span>
                </td>
              </tr>
              <tr>
                <th>昵称：</th>
                <td><input type="text" class="zg_person_text focusBorder"></td>
                </tr>
              <tr>
                <th>手机：</th>
                <td><input type="text" class="zg_person_text focusBorder"></td>
                </tr>
              <tr>
                <th>QQ：</th>
                <td><input type="text" class="zg_person_text focusBorder"></td>
                </tr>
              <tr>
                <th>性别：</th>
                <td>
                	<label class="userInfo_radio"><i class="checked">&nbsp;</i><input type="radio" name="sex" checked>男</label>
                	<label class="userInfo_radio"><i>&nbsp;</i><input type="radio" name="sex">女</label>
                </td>
             </tr>
        </table>
        <input type="submit" value="提交"  class="zg_person_submit">
         </form>
            
        </div>
	</div>
    <!--  我的收藏 end  -->
</div>


<!-- footer  -->
{% include 'public/public_footer.html' %}

ShopMall/templates/home/order_step3.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>无标题文档</title>
<link type="text/css" rel="stylesheet" href="css/pub.css" />
<link type="text/css" rel="stylesheet" href="css/content.css" />
<link type="text/css" rel="stylesheet" href="css/color.css" />
<script src="js/jquery.min.js"></script>

</head>

<body>
<!-- 公共头部 -->
<!--头部-->
<div class="header_w wrap">
	<div class="header cont">
    	<div class="fl">
        	<font>欢迎来小U商城</font>
            <a href="#" alt="">请登录</a><span></span>
            <a href="#" alt="">免费注册</a>
        </div>
        <div class="fr header_r">
        	<a href="#" alt="">我的订单</a><span></span>
            <a href="#" alt="" class="moblieApp">移动APP</a><span></span>
            <a href="#" alt="">网站地图</a><span></span>
            <a href="#" alt="" class="paddingR0">退出</a>
            <div class="mobileApp_QR">
            	<img src="images/mobileApp_QR.jpg" width="140" height="141" >
                <a href="#" class="iphone"><i></i>iphone下载</a>
                <a href="#" class="android"><i></i>Android下载</a>
            </div>
        </div>
    </div>
</div>

<!--头部 end -->

<!--头部 end -->

<div class="order_head_info cont clearfix">
	<a href="#" alt="" class="fl"><img src="images/u_logo.jpg" width="210" height="42"></a><span class="header_title">结算页</span>
	<div class="order_pro clearfix">
    	<span class="pro_pre"><b>1</b>我的购物车</span>
    	<span class="pro_pre"><b>2</b>提交结算</span>
    	<span class="pro_active"><b>3</b>提交成功</span>
    </div>
</div>

<!--付款-->
<div class="order_step3 cont">
	<div class="order3_h clearfix">
    	<div class="order3_hl fl">
        	<img class="fl" src="images/good_s.jpg" width="66" height="66" alt="">
            <p class="order3_p1">订单提交成功，请您尽快付款！</p>
            <p class="order3_p2">订单号：1234567890<br/>请在24小时内完成支付，否则订单会自动取消</p>
        </div>
        <p class="order3_hr fr">支付金额：<font class="price">￥5199.00</font></p>
    </div>
    <div class="order3_c">
        <ul class="zgright-nav-ul fl order3_tabNav">
            <li><a href="#" class="active">储蓄卡</a></li>
            <li><a href="#">信用卡</a></li>
            <li><a href="#">支付宝</a></li>
            <li><a href="#">微信支付</a></li>
        </ul>
    	<div class="order3_tabC" style="display:block;">
        	<ul class="clearfix">
            	<li><img src="images/order3_bank1.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank2.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank3.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank4.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank5.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank6.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank7.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank8.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank9.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank10.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank11.jpg" width="226" height="56" alt=""></li>
            	<li class="moreBank"><a href="#">更多银行</a></li>
            </ul>
        	<a href="javascript:void(0);" class="hover_btn2">立即支付</a>
        </div>
    	<div class="order3_tabC">
        	<ul class="clearfix">
            	<li><img src="images/order3_bank7.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank8.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank9.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank10.jpg" width="226" height="56" alt=""></li>
            	<li><img src="images/order3_bank11.jpg" width="226" height="56" alt=""></li>
            	<li class="moreBank"><a href="#">更多银行</a></li>
            </ul>
        	<a href="javascript:void(0);" class="hover_btn2">立即支付</a>
        </div>
    	<div class="order3_tabC">
        	<ul class="clearfix">
            	<li><img src="images/order3_bank_zfb.jpg" width="226" height="56" alt=""></li>
            </ul>
        	<a href="javascript:void(0);" class="hover_btn2">立即支付</a>
        </div>
    	<div class="order3_tabC order2_pay_wx clearfix">
			<img src="images/order3_wx_QR.jpg" width="192" height="192" alt="">
            <p><i class="order2_wx_icon">&nbsp;</i>请使用微信扫描<br/>二维码以完成支付</p>
        </div>
    </div>

</div>

<!-- 支付提醒 -->
<div class="pay_info_W fixed_shadow_w">
	<div class="fixed_shadow pay_info_shadow"></div>
	<div class="fixed_shadow_c pay_info">
    	<p class="pay_info_t fixed_shadow_ct"><i class="fixed_close pay_info_close">&nbsp;</i>支付提示</p>
    	<p class="pay_info_m fixed_shadow_cm">请您在新打开的网上银行收银台进行支付</p>
        <p class="pay_info_b"><span class="pay_finished">已完成支付</span><a href="javascript:void(0);" class="changeMethod">选择其他方式</a></p>
    </div>
</div>

<!-- footer  -->

<div class="footer_w wrap">
	<div class="footer cont clearfix">
    	<dl>
        	<dt><a href="#" alt="">购物指南</a></dt>
            <dd><a href="#" alt="">购物流程</a></dd>
            <dd><a href="#" alt="">支付方式</a></dd>
            <dd><a href="#" alt="">配送方式</a></dd>
        </dl>    
    	<dl>
        	<dt><a href="#" alt="">售后服务</a></dt>
            <dd><a href="#" alt="">售后政策</a></dd>
            <dd><a href="#" alt="">价格保护</a></dd>
            <dd><a href="#" alt="">退款说明</a></dd>
            <dd><a href="#" alt="">返修/退换货</a></dd>
            <dd><a href="#" alt="">取消订</a></dd>
        </dl>
    	<dl>    
        	<dt><a href="#" alt="">配送方式</a></dt>
            <dd><a href="#" alt="">上门自提</a></dd>
            <dd><a href="#" alt="">211限时达</a></dd>
            <dd><a href="#" alt="">配送服务查询</a></dd>
            <dd><a href="#" alt="">配送费收取标准</a></dd>
            <dd><a href="#" alt="">海外配送</a></dd>
        </dl>
    	<dl>  
        	<dt><a href="#" alt="">支付方式 </a></dt>
            <dd><a href="#" alt="">网上支付</a></dd>
            <dd><a href="#" alt="">支付宝支付</a></dd>
            <dd><a href="#" alt="">邮局汇款</a></dd>
        </dl>     
    	<dl>   
        	<dt><a href="#" alt="">用户帮助</a></dt>
            <dd><a href="#" alt="">免费注册</a></dd>
            <dd><a href="#" alt="">找回密码</a></dd>
            <dd><a href="#" alt="">常见问题</a></dd>
            <dd><a href="#" alt="">优惠券使用</a></dd>
        </dl>  
    </div>
</div>
<p class="copyright">Copyright © 2010-2016 小U商城 版权所有 保留一切权利<br/>京ICP备10218183号 京ICP证161188号 京公网安备 11010802020593号 出版物经营许可证新出发京批字第直130052号</p>
<script src="js/pub.js"></script>
<script src="js/content.js"></script>
</body>
</html>

ShopMall/templates/home/shopping_car.html
{# 继承开始 #}
{% extends 'public/public_head.html' %}


{#    重写开始 #}
{% block middle %}

    {% load staticfiles %}
{#    购物车头#}
    <div class="order_head_info cont clearfix">
        <a href="#" alt="" class="fl"><img src="{% static 'images/u_logo.jpg' %}" width="210" height="42"></a><span
            class="header_title">购物车</span>
        <div class="order_pro clearfix">
            <span class="pro_active"><b>1</b>我的购物车</span>
            <span class="pro_next"><b>2</b>提交结算</span>
            <span class="pro_next"><b>3</b>提交成功</span>
        </div>
    </div>
{#    end#}



    <!--购物车清单-->
    <div class="order1_c cont">
        <form>
            <!-- 购物车清单内容 -->
            <dl>
{#            购物车表头#}
                <dt>
                    <span class="order1_h1"><label class="order1_checkbox order1_checkbox_total"><i></i>全选<input
                            type="checkbox" id="order3_all"></label></span>
                    <span class="order1_h2">商品</span>
                    <span class="order1_h3">单价</span>
                    <span class="order1_h4">购买数量</span>
                    <span class="order1_h5">小计</span>
                    <span class="order1_h6">操作</span>
                </dt>
{#end     #}

{#            内容#}
                {% for x in data %}
<dd class="">{#全选框#}
{#多选框#}
<span class="order1_d1"><label class="order1_checkbox">
    <i class=""></i>   {#单选选框#}
{#   商品图片  #}
<input type="checkbox" id="order3_all" checked></label></span>
                 <span class="order1_d2">
                <div class="list_goods fl">
                    <a href="#"><img src="{{ MEDIA_URL }}{{ x.goods.goods_img_set.first.path }}" width="66" height="66"></a>
                    <p class="list_goods_name"><a href="#">{{ x.goods }}</a></p>
                </div>
                </span>
    {#                          商品单价  #}
                        <span class="order1_d3 order1_h3">￥{{ x.goods.price }}</span>

{#隐藏域                       #}
<input type="hidden" id="price_{{ x.id }}" value="{{ x.goods.price }}">

{#                          购买商品数量加减  #}
<span class="order1_d4 order1_h4"><div class="amount_change">


<b class="invalid" onclick="reduce()">-</b>
{#隐藏域       #}
<input type="text" id="number_{{ x.id }}" value={{ x.number }} data={{ x.id }}>

<b onclick="increase()">+</b>

</div></span>


{#小计价格  #}
<span class="order1_d5 order1_h5" >
    <font id='xiao{{ x.id }}' class="gwc_price"></font>
</span>

                        <span class="order1_h6 order1_d6">
    <a href="#">删除</a> <a href="#">移入收藏夹</a>
</span>


                    </dd>
                {% endfor %}


            </dl>
            <!-- 购物车结算 -->
            <div class="order1_balance clearfix">
                <div class="fl"><span class="order1_h1"><label
                        class="order1_checkbox order1_checkbox_total"><i></i>全选<input type="checkbox"
                                                                                      id="order3_all"></label></span><a
                        href="#">删除选中的商品</a></div>
                <div class="fr order1_bar">
                    <span class="order1_barl fl">已选择<em class="colorB11">1</em>件商品</span>
                    <p class="fr">
                        <span>总价：￥5199.00</span>
                        <span>优惠：￥0.00</span>
                        <span>合计：<font class="price">￥5199.00</font></span>
                    </p>
                </div>
            </div>
            <div class="order1_b"><a href="#" class="hover_btn1">继续购物</a>
                <a href="#" class="hover_btn2">提交结算</a>
            </div>
        </form>
    </div>

    <!-- footer  -->
    {% include 'public/public_footer.html' %}

    <script>
        $(document).ready(
            {#小计 价格#}
            function jisuan() {
                {#    循环所有模糊匹配到的input标签  input[id*='number']  #}
                $("input[id*='number']").each(function () {
                    {#商品数量#}
                    {#alert($(this).val());#}

                    id = $(this).attr('data');
                    {#    当前input标签的商品数量   #}
                    console.log($(this).val());
                    {#  获取当前id的商品价格 #}
                    console.log($('#price_' + id).val());
                    {#   获取乘积   #}

                    console.log($(this).val() * $('#price_' + id).val());

                    {#写  入  #}
                    $('#xiao' + id).html($(this).val() * $('#price_' + id).val());

                })
            }
        )

    </script>


{% endblock %}